name: terraform-plan-approve-apply
on: [push]
jobs:
  prepare-module-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Upload terraform files
        uses: actions/upload-artifact@v2
        with:
          name: tf-files
          path: |
            *.tf
            !integration_tests

  terraform-init-plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: integration_tests/fixtures
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TFE_TOKEN }}

      - name: Download TF module files
        uses: actions/download-artifact@v2
        with:
          name: tf-files
          path: module

      - name: Display structure of downloaded files
        run: ls -l
        working-directory: module

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init -input=false

      - name: Terraform Validate
        id: validate
        run: terraform validate
        continue-on-error: true

      - name: Terraform Plan
        id: plan
        run: terraform plan

      - run: echo ${{ steps.plan.outputs.stdout }}
      - run: echo ${{ steps.plan.outputs.stderr }}
      - run: echo ${{ steps.plan.outputs.exitcode }}
